name: github-contribution-grid-snake

on:
    schedule:
        - cron: "0 */12 * * *"
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    generate:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        
        steps:
            - name: generate animation.svg
              uses: Platane/snk@master
              with:
                  github_user_name: ${{ github.repository_owner }}
                  svg_out_path: dist/github-contribution-grid-snake.svg
            
            - name: push github-contribution-grid-snake.svg to the snake_branch branch
              uses: crazy-max/ghaction-github-pages@v2.5.0
              with:
                  target_branch: snake_branch
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
