name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Life4gal/adworld.xctf-REVERSE@master
      - uses: Life4gal/FromZero2D3D@master
      - uses: Life4gal/VulkanLearning@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
