name: waka-update-readme

on:
    schedule:
        - cron: "0 0 */7 * *"
#     push:
#         branches: [ main ]
    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        # timeout-minutes: 10
        # todo: really?
        environment: Production

        steps:
            - name: Update Readme with Metrics
              uses: anmol098/waka-readme-stats@master
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  GH_TOKEN: ${{ secrets.WAKATIME_GITHUB_KEY }}
                  SHOW_PROJECTS: "False"
                  SHOW_TIMEZONE: "False"
                  SHOW_PROFILE_VIEWS: "False"
                  SHOW_COMMIT: "False"
                  SHOW_DAYS_OF_WEEK: "False"
                  SHOW_OS: "False"
                  SHOW_LINES_OF_CODE: "True"
                  SHOW_TOTAL_CODE_TIME: "True"
            #- name: Update Readme with Metrics
            #  uses: athul/waka-readme@master
            #  with:
            #      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            #      GH_TOKEN: ${{ secrets.WAKATIME_GITHUB_KEY }}
            #      SHOW_TIME: true
            #      SHOW_TOTAL: true
