name: waka-update-readme

on:
    schedule:
        - cron: "0 0 */3 * *"
#     push:
#         branches: [ main ]
    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        # todo: really?
        environment: Production

        steps:
            - name: Update Readme with Metrics
              #uses: anmol098/waka-readme-stats@master
              uses: athul/waka-readme@master
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  GH_TOKEN: ${{ secrets.WAKATIME_GITHUB_KEY }}
                  SHOW_PROJECTS: "False"
                  SHOW_TIMEZONE: "False"
                  SHOW_PROFILE_VIEWS: "False"
                  SHOW_COMMIT: "False"
                  SHOW_DAYS_OF_WEEK: "False"
                  SHOW_OS: "False"
